### ISSUE TITLE
Packet size/type detection failure

### ISSUE THREAD

**Issue by phil-rt** [EarthScope/libslink#10]
In release v2.7.1:

sl_utils.c:
   sl_collect() and sl_clollect_nb():
    (line 209)         (line 618)
        while (slconn->stat->recptr - slconn->stat->sendptr >= SLHEADSIZE + SLRECSIZEMIN)

SLRECSIZEMIN is defined as 48, which only accounts for the fixed header of a miniSEED 2 record and not for any blockettes.
Blockette 1000 contains the record size.
False failures can occur intermittently depending on IP stack packetization and timing.

Increasing SLRECSIZEMIN to 56 to account for the size of blockette 1000 most likely resolves the issue for MOST situations, but NOT ALL since blockette 1000 is not required to be the first blockette in the record.  Additional logic is probably required.

This affects all programs that use libslink v2.7.1.  i.e;
   SLINKTOOL v4.5.0
   SLARCHIVE v2.3

**Comment by chad-earthscope** [comment]
This should be fixed in the new major version release v4.0.0.
