### ISSUE TITLE
Is it possible to port to embedded systems?

### ISSUE THREAD

**Issue by KOUKILEO** [EarthScope/libslink#11]
Is it possible to port it to embedded systems? For example, ESP32, STM32, or similar microcontrollers. Or any solutions?

**Comment by chad-earthscope** [comment]
I do not know as I have never used any of those kinds of microcontrollers and I have not heard of anyone doing so.  The library is pretty simple C99 code, and only needs the standard C library and a UNIX-like socket network API.  So if that can be compiled for such systems it should work.
