### ISSUE TITLE
/usr/bin/ld: cannot open linker script file libslink.map: No such file or directory

### ISSUE THREAD

**Issue by morealaz** [EarthScope/libslink#7]
Hi there,
I tried to compile **libslink** 2.7 on Arch Linux and got following error from `ld` linker:

`/usr/bin/ld: cannot open linker script file libslink.map: No such file or directory`

Apparently there is no `libslink.map` file.

**Comment by chad-earthscope** [comment]
Fixed in #36cb245995ecfb4f5c9c886d0822b8a6be0ce03f
