### ISSUE TITLE
Makefile: install man files

### ISSUE THREAD

**Issue by morealaz** [EarthScope/libslink#8]
Hi there,
Could you change the `Makefile` install section to also install man-pages?
thanks.

**Comment by chad-earthscope** [comment]
Hi @morealaz, thanks for the suggestion.  I would rather not add this for the following reasons: the next major release will not have man pages (instead generated documentation in HTML, etc.), this now end-of-life version has never installed them, and so there should be no increased expectation for man pages.  My hope is that this version of the library is replaced as fast as possible with the next major release.
