### ISSUE TITLE
it will coredump if senptr > recptr in memmove function in slutils.c

### ISSUE THREAD

**Issue by wangmm0220** [EarthScope/libslink#9]
In the branch of develop.

(slconn->stat->slpack.reclen > 0 && slconn->stat->slpack.reclen > bufferlen))  should be (slconn->stat->slpack.reclen > 0 && slconn->stat->slpack.reclen + SLHEADSIZE > bufferlen))

otherwise  sendptr will be bigger than recptr
send:1560, rec:1556

**Comment by chad-earthscope** [comment]
Thanks @wangmm0220.  That should be protected against.  

Out of curiosity, have you see this scenario occur?  If so, what were the circumstances?  Thanks.

**Comment by chad-earthscope** [comment]
This should be fixed in the new major release.
